# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 16:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='projects.CatalogItem')),
                ('project', models.ManyToManyField(to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TestRailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField()),
                ('test_suite', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TestRailInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='testcasehistory',
            name='project',
        ),
        migrations.DeleteModel(
            name='TestCaseHistory',
        ),
        migrations.AddField(
            model_name='testrailconfiguration',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.TestRailInstance'),
        ),
        migrations.AddField(
            model_name='project',
            name='testrail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.TestRailConfiguration'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogitem',
            unique_together=set([('parent', 'name')]),
        ),
    ]
