# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_module_testcasehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('project', 'name')]),
        ),
    ]
