# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160727_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='project',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
    ]
