# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160802_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='catalog',
            field=models.ManyToManyField(blank=True, to='projects.CatalogItem'),
        ),
    ]
