# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160802_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='catalog',
            field=models.ManyToManyField(blank=True, to='projects.CatalogItem'),
        ),
    ]
