# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_module_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrailconfiguration',
            name='project_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
