# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_testrailconfiguration_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrailconfiguration',
            name='project_name',
            field=models.TextField(unique=True),
        ),
    ]
