# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 18:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160811_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrailconfiguration',
            name='test_suite',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), blank=True, size=None),
        ),
    ]
