# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20160811_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='testrailconfiguration',
            options={'ordering': ['project_name']},
        ),
    ]
