# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160826_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrailconfiguration',
            name='instance',
        ),
        migrations.AlterField(
            model_name='project',
            name='testrail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testcases.TestRailConfiguration'),
        ),
        migrations.DeleteModel(
            name='TestRailConfiguration',
        ),
        migrations.DeleteModel(
            name='TestRailInstance',
        ),
    ]
