# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0007_auto_20160817_1432'),
        ('projects', '0012_auto_20160829_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('origin_type', models.IntegerField(choices=[(1, 'TestHeader'), (2, 'PreCondition'), (3, 'Prompt'), (4, 'Data')], default=1)),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graphs.Node')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectvariable',
            unique_together=set([('project', 'name')]),
        ),
    ]
