# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-22 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20160830_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('root_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='test_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_header', to='projects.Module'),
        ),
        migrations.AddField(
            model_name='language',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_projects', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_language', to='projects.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together=set([('project', 'name')]),
        ),
    ]
