# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-23 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20170222_1216'),
        ('projects', '0014_vuid'),
    ]

    operations = [
    ]
