# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-24 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='language'),
        ),
    ]
