# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-25 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20170404_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
