# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-01 16:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20171101_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdatabaseset',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
