# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-26 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField()),
                ('remote_user', models.TextField()),
                ('remote_password', models.TextField()),
                ('name', models.TextField(unique=True)),
            ],
        ),
    ]
