# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-20 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import mdta.apps.runner.models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HatitFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('upload', models.FileField(upload_to=mdta.apps.runner.models.hatitfile_location)),
                ('suiteID', models.TextField()),
            ],
        ),
    ]
