# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_testrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestServers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.TextField()),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TestServer',
        ),
    ]
