# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_auto_20170426_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testrail_case_id', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Incomplete'), (2, 'Pass'), (3, 'Fail')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='testrun',
            name='hat_server',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='runner.TestServers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrun',
            name='testrail_test_run',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automatedtestcase',
            name='test_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.TestRun'),
        ),
    ]
