# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-04 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0005_auto_20170426_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtestcase',
            name='case_title',
            field=models.TextField(default=''),
        ),
    ]
