# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-04 20:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0006_automatedtestcase_case_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testservers',
            name='server_url',
            field=models.TextField(default='', validators=[django.core.validators.URLValidator()]),
        ),
    ]
