# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0007_testservers_server_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testservers',
            name='server_url',
            field=models.TextField(default=''),
        ),
    ]
