# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0008_auto_20170505_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtestcase',
            name='tr_test_id',
            field=models.TextField(default=''),
        ),
    ]
