# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0010_auto_20170505_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtestcase',
            name='script',
            field=models.TextField(default=''),
        ),
    ]
