# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0014_auto_20170509_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedtestcase',
            name='scripts',
        ),
    ]
