# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0016_automatedtestcase_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedtestcase',
            name='script',
        ),
    ]
