# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0017_remove_automatedtestcase_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtestcase',
            name='case_script',
            field=models.TextField(default=''),
        ),
    ]
