# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graphs', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='edge',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_node', to='graphs.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.Module'),
        ),
        migrations.AddField(
            model_name='edge',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_node', to='graphs.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.EdgeType'),
        ),
    ]
