# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_remove_edge_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='property',
            new_name='properties',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='property',
            new_name='properties',
        ),
    ]
