# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_auto_20160607_1211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set([('module', 'name')]),
        ),
    ]
