# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0006_remove_edge_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edgetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='nodetype',
            options={'ordering': ['name']},
        ),
    ]
