# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 18:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0007_auto_20160817_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgetype',
            name='subkeys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='SubKeys(Separated with comma)'),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='subkeys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='SubKeys(Separated with comma)'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
