# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0009_auto_20170222_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
    ]
