# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-25 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0010_auto_20170316_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='celery_visited',
            field=models.TextField(default=False),
        ),
    ]
