# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_testcaseresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasehistory',
            name='project',
        ),
        migrations.DeleteModel(
            name='TestCaseHistory',
        ),
    ]
