# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 15:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20160504_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='edgetype',
            name='keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='Keys(Separated with comma)'),
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='Keys(Separated with comma)'),
        ),
    ]
